import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MinimizableWebChat from "@/components/chat/MinimizableWebChat";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        {/* <a href="#">
          <img
            className="my-button"
            src="https://assets.stickpng.com/images/580b57fcd9996e24bc43c543.png"
          />
        </a> */}
        <MinimizableWebChat />
        <Script src="https://aka.ms/csspeech/jsbrowserpackageraw" />
        <Script src="/synthesis.js" />
        <Script src="/microphone.js" />
      </body>
    </html>
  );
}
